### ISSUE TITLE
在容器中运行一直报错 不清楚原因 望解惑

### ISSUE THREAD

**Issue by zhangyiming748** [Abyxs/ResuBlocks#1]
# 直接使用compose文件部署

```yml
services:
  resume:
    image: zhangyiming748/resublocks:latest
    container_name: resume
    ports:
      - "5173:5173"
    restart: unless-stopped
```

dockerfile如下

```
FROM node:18-alpine
WORKDIR /app
COPY . .
# 主项目依赖
RUN npm install
# 进入应用目录安装依赖
WORKDIR /app/resume-app
RUN npm install
EXPOSE 5173
ENTRYPOINT ["npm","run","dev"]
# 或
# yarn dev
# docker run -it --rm --name test -v /Users/zen/github/ResuBlocks:/app -p 5173:5173 node:18-alpine ash
```

docker logs 输出

```bash
  VITE v4.5.13  ready in 130 ms

  ➜  Local:   http://localhost:5173/
  ➜  Network: use --host to expose
  ➜  press h to show help
```

浏览器访问报错

![](https://cdn.ldstatic.com/optimized/4X/5/a/f/5afa27952f54dffd35c9457c8711e3a5a135d732_2_1380x896.jpeg)

# 使用docker run 逐步复现

```bash
docker run -it --rm --name test -v /Users/zen/github/ResuBlocks:/app -p 5173:5173 node:18-alpine ash
cd app
npm install
cd resume-app
npm install
npm run dev

```

终端输出

```bash
  VITE v4.5.13  ready in 130 ms

  ➜  Local:   http://localhost:5173/
  ➜  Network: use --host to expose
  ➜  press h to show help
```
浏览器访问依旧报错
![](https://cdn.ldstatic.com/optimized/4X/5/a/f/5afa27952f54dffd35c9457c8711e3a5a135d732_2_1380x896.jpeg)
